# Generated by Django 4.2 on 2023-04-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
